version: '3.9'
services:
  db:
    image: postgres:14
    env_file: ./server/.env
    expose:
      - '5432'
    user: postgres
    volumes:
      - db:/home/postgresql/data
      - ./server/utils:/docker-entrypoint-initdb.d

  server:
    env_file: ./server/.env
    build: ./server/ # look for Dockerfile and build
    ports:
      - '8080:8080'
    volumes:
      - ./server/:/home/server # copyinh server dir
      - /home/server/node_modules 

  client:
    # env_file: .env
    build: ./client/ # look for Dockerfile and build
    ports:
      - '3000:3000'
    volumes:
      - ./client/:/home/client
      - /home/client/node_modules 
    depends_on:
        - server
volumes:
  db: